Vacations/src/views/about_view.py
from flask import Blueprint, render_template

# Managing the entire view
about_blueprint = Blueprint("about_view", __name__) # "about_view" is the name of the view


@about_blueprint.route("/about") # Route
def about(): # View Function
    return render_template("about.html", active = "about")

Vacations/src/views/auth_view.py
from flask import Blueprint, jsonify, render_template, redirect, url_for, request, session
from facades.auth_facade import AuthFacade
from models.client_errors import ValidationError, AuthError

# Managing the entire view
auth_blueprint = Blueprint("auth_view", __name__)

# Create auth facade: 
auth_facade = AuthFacade()


# Register new user:
@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    try:
        if request.method == "GET": return render_template("register.html", user = {})
        auth_facade.register()
        return redirect(url_for("home_view.home"))
    except ValidationError as err:
        return render_template("register.html", error = err.message, user = err.model)


# Login existing user:
@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    try:
        if request.method == "GET": 
            err = request.args.get("error") # Take error from url (if exists)
            return render_template("login.html", error = err, credentials = {})
        auth_facade.login()
        return redirect(url_for("home_view.home"))
    except (ValidationError, AuthError) as err:
        return render_template("login.html", error = err.message, credentials = err.model)

# Logout user:
@auth_blueprint.route("/logout")
def logout():
    auth_facade.logout()
    return redirect(url_for("home_view.home"))

# Fetch session data
@auth_blueprint.route("/get-session-data")
def get_session_data():
    return jsonify(session)


Vacations/src/views/holidays_view.py
from flask import Blueprint, render_template, send_file, redirect, url_for, request, jsonify, session
from facades.holiday_facade import HolidayFacade
from facades.auth_facade import AuthFacade
from models.role_model import RoleModel
from utils.image_handler import ImageHandler
from models.client_errors import ResourceNotFoundError, ValidationError, AuthError
from datetime import date

# Managing the entire view
holidays_blueprint = Blueprint("holidays_view", __name__) # "holidays_view" is the name of the view

# Create facade: 
holidays_facade = HolidayFacade()
auth_facade = AuthFacade()

@holidays_blueprint.route("/holidays") # Route
def user_list(): # View Function
    try:
        auth_facade.block_anonymous()
        user = session.get("current_user")
        holidays_facade.get_liked_holidays_for_holiday(user)
        holidays = holidays_facade.get_all_holidays_with_likes_count()
        error = request.args.get("error")
        if user["role_id"] == RoleModel.User.value:
            return render_template("user_holidays.html", holidays=holidays, error=error, active="user_list")
        return render_template("admin_holidays.html", holidays=holidays, error=error, active="user_list")
    except AuthError as err: 
        return redirect(url_for("auth_view.login", error=err.message)) # Send error to url query string

@holidays_blueprint.route("/holidays/admin")
def admin_list():
    try:
        auth_facade.block_non_admin()
        all_holidays = holidays_facade.get_all_holidays()
        return render_template("admin_holidays.html", holidays=all_holidays, active="admin_list")
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message)) 


# Display single holiday:
@holidays_blueprint.route("/holidays/details/<int:id>") # <int:id> is called a route parameter
def details(id):
    try:
        auth_facade.block_anonymous()
        one_holiday = holidays_facade.get_one_holiday(id)
        return render_template("details.html", holiday = one_holiday)
    except AuthError as err: 
        return redirect(url_for("auth_view.login", error = err.message)) 
    except ResourceNotFoundError as err:
        return render_template("404.html", error = err.message)

# Return image file:
@holidays_blueprint.route("/holidays/images/<string:image_name>")
def get_image(image_name):
    image_path = ImageHandler.get_image_path(image_name)
    return send_file(image_path) # Returns a complete file (an image file with pixels of the image...)

# Adding new holiday:
@holidays_blueprint.route("/holidays/new", methods=["GET", "POST"])
def insert():
    try:
        auth_facade.block_non_admin()
        if request.method == "GET": 
            # Fetch countries
            all_cities = holidays_facade.get_all_cities()
            current_date = date.today().isoformat()
            return render_template("insert.html", cities=all_cities, active="insert", current_date=current_date)
        holidays_facade.add_holiday()
        return redirect(url_for("holidays_view.admin_list"))
    except AuthError as err: 
        return redirect(url_for("auth_view.login", error=err.message)) # Send error to url query string
    except ValidationError as err:
        all_cities = holidays_facade.get_all_cities()  # Fetch cities again
        return render_template("insert.html", cities=all_cities, error=err.message)


# Updating existing holiday:
@holidays_blueprint.route("/holidays/edit/<int:id>", methods=["GET", "POST"])
def edit(id):
    try:
        auth_facade.block_non_admin()
        if request.method == "GET": 
            all_cities = holidays_facade.get_all_cities()
            one_holiday = holidays_facade.get_one_holiday(id)
            image_name = one_holiday['image_name']  # Assuming 'image_name' is the column name in your database
            return render_template("edit.html", cities=all_cities, holiday = one_holiday, image_name=image_name,)
        holidays_facade.update_holiday()
        return redirect(url_for("holidays_view.admin_list"))
    except AuthError as err: 
        return redirect(url_for("auth_view.login", error = err.message)) # Send error to url query string
    except ResourceNotFoundError as err:
        return render_template("404.html", error = err.message) 
    except ValidationError as err:
        all_cities = holidays_facade.get_all_cities()  # Fetch cities again
        return render_template("edit.html", cities=all_cities, error = err.message, holiday = err.model)

# Delete existing holiday:
@holidays_blueprint.route("/holidays/delete/<int:id>")
def delete(id):
    try:
        auth_facade.block_non_admin()
        holidays_facade.delete_holiday(id)
        return redirect(url_for("holidays_view.admin_list"))
    except AuthError as err: 
        return redirect(url_for("auth_view.login", error = err.message)) # Send error to url query string


# Get data and updates likes table
@holidays_blueprint.route("/holidays/update-likes", methods=["POST"])
def update_likes():
    try:
        data = request.json
        holidays_facade.update_likes(data)
        return jsonify({"message": "Like added"}), 200
    except Exception as err:
        return jsonify({"error": str(err)}), 400  # Return 400 Bad Request on error
    

Vacations/src/views/home_view.py
from flask import Blueprint, render_template

# Managing the entire view
home_blueprint = Blueprint("home_view", __name__) # "home_view" is the name of the view


@home_blueprint.route("/") # Route
@home_blueprint.route("/home") # Route
def home(): # View Function
    return render_template("home.html", active = "home")


Vacations/src/templates/about.html
{% extends "layout.html" %}

{% block title %}DreamEscapeEnjoy | About{% endblock title %}

{% block content %}
<h2>Your next trip is a click away from
<a {% if active == 'user_list' %}active{% endif %}" href="{{ url_for('holidays_view.user_list') }}" {% if active=='user_list' %} class="active" {% endif %}>you!</a>
</h2>

<img width="600px" height="500px" src="{{ url_for('static', filename='images/tropical.jpeg') }}" alt="Image Icon" width="20" height="20">

<br>



{% endblock content %}

Vacations/src/templates/admin_holidays.html
{% extends "layout.html" %}

{% block title %}DreamEscapeEnjoy | Holidays{% endblock title %}

{% block content %}
<div class="container">
    {% for row in holidays|batch(3) %}
    <div class="row">
        {% for h in row %}
        <div class="col-md-4">
            <div class="card" style="width: 25rem;">
                <a class="editBtn likeBtn btn btn-outline-secondary" href="{{ url_for('holidays_view.edit', id = h.id) }}">Edit<i class="bi bi-pencil-square"></i></a>
                <a class="deleteBtn likeBtn btn btn-outline-secondary" onclick="confirmDelete()" href="{{ url_for('holidays_view.delete', id = h.id) }}">Delete<i class="bi bi-trash"></i></a>
                <a id="noUnderLine" href="{{ url_for('holidays_view.details', id=h.id) }}">
                    <img src="{{ url_for('holidays_view.get_image', image_name=(h.image_name if h.image_name else '---')) }}" class="card-img-top">
                    <h5 class="card-title">
                        {{ h.city }} 
                    </h5>
                    <div class="holiday-dates bi bi-calendar-event">{{ h.start_date }} - {{ h.end_date }}</div>
                    <div class="card-body">
                        <p class="card-text">{{ h.description }}</p>
                        <div class="holiday-price" href="{{ url_for('holidays_view.details', id=h.id) }}">${{ h.price }}</div>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock content %}

Vacations/src/templates/auth.html
<div>

    {% if user %}

        <span>Hello {{user["first_name"]}} {{user["last_name"]}}</span>
        <span> | </span>
        <a href="{{ url_for('auth_view.logout') }}">Logout</a>

    {% else %}

        <span>Hello Guest</span>
        <span> | </span>
        <a href="{{ url_for('auth_view.login') }}">Login</a>
        <span> | </span>
        <a href="{{ url_for('auth_view.register') }}">Register</a>

    {% endif %}

</div>

Vacations/src/templates/copyuser_holidays copy.html
{% extends "layout.html" %}

{% block title %}DreamEscapeEnjoy | Holidays{% endblock title %}

{% block content %}

<div class="container">
    {% for row in holidays|batch(3) %}
    <div class="row">
        {% for h in row %}
        <div class="col-md-4">
            <div class="card" style="width: 25rem;">
                <span onclick="changeLikeStatus(this)" class="likeBtn btn btn-outline-secondary">
                    <i class=" i bi-heart-fill"></i> Like
                </span>
                <a id="noUnderLine" href="{{ url_for('holidays_view.details', id = h.id ) }}">
                    <img src="{{ url_for('holidays_view.get_image', image_name=(h.image_name if h.image_name else '---')) }}"
                        class="card-img-top">
                    <span class="something">{{h.likes}}</span>
                    <h5 class="card-title">{{ h.city }}</h5>
                    <div class="holiday-dates bi bi-calendar-event">{{ h.start_date }} - {{ h.end_date }}</div>
                    <div class="card-body">
                        <p class="card-text">{{ h.description }}</p>
                        <div class="holiday-price" href="{{ url_for('holidays_view.details', id = h.id ) }}">${{ h.price }}</div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>


{% endblock content %}

Vacations/src/templates/details.html
{% extends "layout.html" %}

{% block title %}Holiday Details{% endblock title %}

{% block content %}
<div class="holiday-details-container">
    <div>
        <img id="detailsPic" src="{{ url_for('holidays_view.get_image', image_name = (holiday.image_name if holiday.image_name else '---') ) }}">
    </div>
    <div class="details">
        <h5>City: {{ holiday.city }}🛬🛫</h5>
        <h5>Start Date: {{ holiday.start_date }}🗓</h5>
        <h5>End Date: {{ holiday.end_date }}🗓</h5>
        <h5>Price: ${{ holiday.price }}</h5>
    </div>
</div>
<div class="description-container">
    <h5>Holiday Description:</h5>
    <p>{{ holiday.description }}</p>
</div>
<a href="{{ url_for('holidays_view.user_list') }}">Back</a>
{% endblock content %}

Vacations/src/templates/edit.html
{% extends "layout.html" %}

{% block title %}Edit Holiday{% endblock title %}

{% block content %}

<form method="post" class="fancy-form" enctype="multipart/form-data">
    <h2 class="header">Edit Vacation</h2>


    <input type="hidden" name="id" value="{{ holiday.id }}">

    <label>Country: </label>
    <select class="form-select" name="city_id" id="city">
        {% for city in cities %}
            {% if city.id == holiday.city_id %}
                <option value="{{ city.id }}" selected>{{ city.city }}</option>
            {% else %}
                <option value="{{ city.id }}">{{ city.city }}</option>
            {% endif %}
        {% endfor %}
    </select>
    

    <label>Description: </label>
    <textarea name="description" class="form-control">{{ holiday.description }}</textarea>

    <label>Price: </label>
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">$</span>
        </div>
        <input type="text" name="price" class="form-control" value="{{ holiday.price }}" placeholder="$">
    </div>

    <label>Start Date: </label>
    <input type="date" name="start_date" class="form-control" value="{{ holiday.start_date }}" required min="{{ current_date }}">

    <label>End Date: </label>
    <input type="date" name="end_date" class="form-control" value="{{ holiday.end_date }}" required min="{{ current_date }}">


    
    <label>Cover Image:</label>
    <br>
    <label for="imageInput" class="file-label">
        <img id="previewImage" src="{{ url_for('static', filename='images/holidays/' ~ holiday.image_name) }}">
        <span>Select Image</span>
    </label>
    <input type="file" name="image" accept="image/*" id="imageInput" class="hidden-input">

    
    <button class="btn btn-primary w-100">Update</button>
    <br><br>
    <a class="cancelButton" href="{{ url_for('holidays_view.admin_list') }}">Cancel</a>

    
</form>

{% endblock content %}

Vacations/src/templates/home.html
{% extends "layout.html" %}

{% block title %}DreamEscapeEnjoy | Home{% endblock title %}

{% block content %}

<h2>Welcome to DreamEscapeEnjoy</h2>
<br>
<h5>🛫🏰Your gateway to heaven on earth: Discover, Escape, Explore🏖🛬</h5>

<br>
<!-- <img class="image" width="800" height="400" src="{{ url_for('static', filename='images/Paradise.jpeg') }}"> -->
<iframe width="560" height="315" src="https://www.youtube.com/embed/exI_hD_4jAM?si=GLOG5xqY94jz7Ro9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

{% endblock content %}

Vacations/src/templates/insert.html
{% extends "layout.html" %}

{% block title %}Add Holiday{% endblock title %}

{% block content %}

<form method="post" class="fancy-form" enctype="multipart/form-data">

    <h2 class="header">Add Vacation</h2>


    <!-- City Selector -->
    <label>Country:</label>
    <select class="form-select" name="city_id" id="city" required>
        <option value="">--Select--</option>
        {% for city in cities %}
            <option value="{{ city.id }}" {% if request.form.city_id == city.id %}selected{% endif %}>{{ city.city }}</option>
        {% endfor %}
    </select>

    <label>Description: </label>
    <textarea name="description" class="form-control" required min="10" max="1000">{{ request.form.description }}</textarea>

    <label>Start Date: </label>
    <input type="date" name="start_date" class="form-control" required min="{{ current_date }}" value="{{ request.form.start_date }}">

    <label>End Date: </label>
    <input type="date" name="end_date" class="form-control" required min="{{ current_date }}" value="{{ request.form.end_date }}">

    <label>Price: </label>
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">$</span>
        </div>
        <input type="text" name="price" class="form-control" required placeholder="$" value="{{ request.form.price }}">
    </div>
<!--     
    <label>Cover image: </label>
    <input type="file" name="image" accept="image/*" class="form-control" required> -->

    
    <label>Cover Image:</label>
    <br>
    <label for="imageInput" class="file-label">
        <img id="previewImage" src="{{ url_for('static', filename='images/no-image.jpeg')}}" alt="Preview Image" >
        <span>Select Image</span>
    </label>
    <input type="file" name="image" accept="image/*" id="imageInput" class="hidden-input">
    
    <button class="btn btn-primary w-100">Add</button>
    
</form>

{% endblock content %}

Vacations/src/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/winter.png') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script defer src="{{ url_for('static', filename='js/main.js')}}"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>

    <!-- Get the user from the session for later use: -->
    {% set user = session.get("current_user") %}

    <div class="layout">


        <header>
            {% include "nav.html" %}
        </header>

        <main>
            <!-- Place holder for a block named "content" specified in the pages: -->
            {% block content %}
            {% endblock content %}

            {% if error %} <span class="error">{{error}}</span> {% endif %}

        </main>

        <footer>
            <div>All Rights Reserved ®️©</div>
        </footer>

    </div>

</body>

</html>

Vacations/src/templates/login.html
{% extends "layout.html" %}

{% block title %}Login{% endblock title %}

{% block content %}

<form method="post" class="fancy-form">

    <h2 class="header">Login</h2>

    <label>Email: </label>
    <input type="email" name="email" value="{{credentials.email}}" class="form-control" required minlength="5"
        maxlength="100">

    <label>Password: </label>
    <input type="password" name="password" value="{{credentials.password}}" class="form-control" required minlength="4"
        maxlength="100">

    <button class="btn btn-primary w-100">Login</button>
    <br><br>

    <span>don't have an account?</span>

    <br>
    <a href="{{ url_for('auth_view.register') }}">register now</a>



</form>

{% endblock content %}

Vacations/src/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">

        <a class="navbar-brand" href="{{ url_for('home_view.home') }}">DreamEscapeEnjoy</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if active == 'home' %}active{% endif %}" aria-current="page" href="{{ url_for('home_view.home') }}" {% if active=='home' %} class="active" {% endif %}>Home</a>
                </li>
                {% if user %}
                    {% if user.role_id == 2 %}
                        <li class="nav-item">
                            <a class="nav-link {% if active == 'user_list' %}active{% endif %}" href="{{ url_for('holidays_view.user_list') }}" {% if active=='user_list' %} class="active" {% endif %}>Holidays</a>
                        </li>
                    {% endif %}
                    {% if user.role_id == 1 %}
                        <li class="nav-item">
                            <a class="nav-link {% if active == 'admin_list' %}active{% endif %}" href="{{ url_for('holidays_view.admin_list') }}" {% if active=='admin_list' %} class="active" {% endif %}>Holidays</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if active == 'insert' %}active{% endif %}" href="{{ url_for('holidays_view.insert') }}" {% if active=='insert' %} class="active" {% endif %}>Add New Holiday</a>
                        </li>
                    {% endif %}
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link {% if active == 'about' %}active{% endif %}" href="{{ url_for('about_view.about') }}" >About</a>
                </li>
            </ul>

            <div class="auth btn">
                {% include "auth.html" %}
            </div>

        </div>
    </div>
</nav>

Vacations/src/templates/register.html
{% extends "layout.html" %}

{% block title %}Register{% endblock title %}

{% block content %}

<form method="post" class="fancy-form">

    <h2 class="header">Register</h2>

    <label>First name: </label>
    <input type="text" name="first_name" value="{{user.first_name}}" class="form-control" required minlength="2" maxlength="20">

    <label>Last name: </label>
    <input type="text" name="last_name" value="{{user.last_name}}" class="form-control" required minlength="2" maxlength="30">

    <label>Email: </label>
    <input type="email" name="email" value="{{user.email}}" class="form-control" required minlength="5" maxlength="100">

    <label>Password: </label>
    <input type="password" name="password" value="{{user.password}}" class="form-control" required minlength="4" maxlength="100">

    <button class="btn btn-primary w-100">Register</button>
    <br><br>
    
    <span>already a member?</span>

    <br>
    <a href="{{ url_for('auth_view.login') }}">login</a>

    
</form>

{% endblock content %}

Vacations/src/templates/user_holidays.html
{% extends "layout.html" %}

{% block title %}DreamEscapeEnjoy | Holidays{% endblock title %}

{% block content %}
<div class="container">
    {% for row in holidays|batch(3) %}
    <div class="row">
        {% for h in row %}
        <div class="col-md-4">
            <div class="card" style="width: 25rem;">
                <div class=" likes likeBtn btn btn-outline-secondary" data-id="{{ h.id }}" onclick="changeLikeStatus(this)">
                    <i class=" i bi-heart-fill"></i>
                    Like
                    <span>
                    {{ h.likes }}
                    </span>
                </div>
                <a id="noUnderLine" href="{{ url_for('holidays_view.details', id=h.id) }}">
                    <img src="{{ url_for('holidays_view.get_image', image_name=(h.image_name if h.image_name else '---')) }}" class="card-img-top">
                    <h5 class="card-title">
                        {{ h.city }}🛩
                    </h5>
                    <div class="holiday-dates bi bi-calendar-event">{{ h.start_date }} - {{ h.end_date }}</div>
                    <div class="card-body">
                        <p class="card-text">{{ h.description }}</p>
                        <div class="holiday-price" href="{{ url_for('holidays_view.details', id=h.id) }}">${{ h.price }}</div>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock content %}